// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5574192560812130677),
    name: 'Budget',
    lastPropertyId: const obx_int.IdUid(8, 6053026932893744209),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9214551649342974907),
        name: 'localId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 250283273511774905),
        name: 'serverId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 1611183756185313815),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2957790525640468579),
        name: 'dbCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1846827314384648180),
        name: 'limitAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3827219914486052508),
        name: 'month',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2113386748042865743),
        name: 'year',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8965088058634930978),
        name: 'spent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6053026932893744209),
        name: 'remaining',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4394803372386859630),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(7, 5012737802703416520),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 379436739435847804),
        name: 'localId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5912430042268565551),
        name: 'serverId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 827320364083288677),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3683141746072158620),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 65105620817157698),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4307695167974047121),
        name: 'dbCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5611710202612279442),
        name: 'dbType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5012737802703416520),
        name: 'dateMilliseconds',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4394803372386859630),
    lastIndexId: const obx_int.IdUid(2, 827320364083288677),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Budget: obx_int.EntityDefinition<Budget>(
      model: _entities[0],
      toOneRelations: (Budget object) => [],
      toManyRelations: (Budget object) => {},
      getId: (Budget object) => object.localId,
      setId: (Budget object, int id) {
        object.localId = id;
      },
      objectToFB: (Budget object, fb.Builder fbb) {
        final serverIdOffset = object.serverId == null
            ? null
            : fbb.writeString(object.serverId!);
        final dbCategoryOffset = fbb.writeString(object.dbCategory);
        fbb.startTable(9);
        fbb.addInt64(0, object.localId);
        fbb.addOffset(1, serverIdOffset);
        fbb.addOffset(2, dbCategoryOffset);
        fbb.addFloat64(3, object.limitAmount);
        fbb.addInt64(4, object.month);
        fbb.addInt64(5, object.year);
        fbb.addFloat64(6, object.spent);
        fbb.addFloat64(7, object.remaining);
        fbb.finish(fbb.endTable());
        return object.localId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final localIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final dbCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final limitAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final monthParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final yearParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final spentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final remainingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = Budget(
          localId: localIdParam,
          serverId: serverIdParam,
          dbCategory: dbCategoryParam,
          limitAmount: limitAmountParam,
          month: monthParam,
          year: yearParam,
          spent: spentParam,
          remaining: remainingParam,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[1],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.localId,
      setId: (Transaction object, int id) {
        object.localId = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final serverIdOffset = object.serverId == null
            ? null
            : fbb.writeString(object.serverId!);
        final descriptionOffset = fbb.writeString(object.description);
        final dbCategoryOffset = fbb.writeString(object.dbCategory);
        final dbTypeOffset = fbb.writeString(object.dbType);
        fbb.startTable(8);
        fbb.addInt64(0, object.localId);
        fbb.addOffset(1, serverIdOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, dbCategoryOffset);
        fbb.addOffset(5, dbTypeOffset);
        fbb.addInt64(6, object.dateMilliseconds);
        fbb.finish(fbb.endTable());
        return object.localId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final localIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final serverIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dbCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final dbTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final dateMillisecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = Transaction(
          localId: localIdParam,
          serverId: serverIdParam,
          amount: amountParam,
          description: descriptionParam,
          dbCategory: dbCategoryParam,
          dbType: dbTypeParam,
          dateMilliseconds: dateMillisecondsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Budget] entity fields to define ObjectBox queries.
class Budget_ {
  /// See [Budget.localId].
  static final localId = obx.QueryIntegerProperty<Budget>(
    _entities[0].properties[0],
  );

  /// See [Budget.serverId].
  static final serverId = obx.QueryStringProperty<Budget>(
    _entities[0].properties[1],
  );

  /// See [Budget.dbCategory].
  static final dbCategory = obx.QueryStringProperty<Budget>(
    _entities[0].properties[2],
  );

  /// See [Budget.limitAmount].
  static final limitAmount = obx.QueryDoubleProperty<Budget>(
    _entities[0].properties[3],
  );

  /// See [Budget.month].
  static final month = obx.QueryIntegerProperty<Budget>(
    _entities[0].properties[4],
  );

  /// See [Budget.year].
  static final year = obx.QueryIntegerProperty<Budget>(
    _entities[0].properties[5],
  );

  /// See [Budget.spent].
  static final spent = obx.QueryDoubleProperty<Budget>(
    _entities[0].properties[6],
  );

  /// See [Budget.remaining].
  static final remaining = obx.QueryDoubleProperty<Budget>(
    _entities[0].properties[7],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.localId].
  static final localId = obx.QueryIntegerProperty<Transaction>(
    _entities[1].properties[0],
  );

  /// See [Transaction.serverId].
  static final serverId = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[1],
  );

  /// See [Transaction.amount].
  static final amount = obx.QueryDoubleProperty<Transaction>(
    _entities[1].properties[2],
  );

  /// See [Transaction.description].
  static final description = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[3],
  );

  /// See [Transaction.dbCategory].
  static final dbCategory = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[4],
  );

  /// See [Transaction.dbType].
  static final dbType = obx.QueryStringProperty<Transaction>(
    _entities[1].properties[5],
  );

  /// See [Transaction.dateMilliseconds].
  static final dateMilliseconds = obx.QueryIntegerProperty<Transaction>(
    _entities[1].properties[6],
  );
}
