name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Create empty .env file
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Install ObjectBox C library (for tests)
        run: bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)

      - name: Run tests
        run: flutter test
