name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        run: |
          curl -fsSL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.29.3-stable.tar.xz | tar -xJ -C $HOME
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          git config --global --add safe.directory "$HOME/flutter"

      - name: Set up environment config
        run: cp .env.example .env

      - name: Install dependencies
        run: flutter pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed lib test

      - name: Run Flutter Analyzer
        run: flutter analyze

      - name: Install ObjectBox C library (for tests)
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/objectbox/objectbox-dart/v4.3.1/install.sh) --install
          rm -f lib/libobjectbox.so

      - name: Run tests
        run: flutter test
